#!/bin/bash

name=$1

fname=$(echo $name | tr '[:upper:]' '[:lower:]')_A.go

echo "package glui" > $fname

echo "func (e *$name) A(children ...Element) Element {" >> $fname
echo "  for _, child := range children {" >> $fname
echo "    e.ElementData.appendChild(child)" >> $fname
echo "    child.RegisterParent(e)" >> $fname
echo "  }" >> $fname
echo "  return e" >> $fname
echo "}" >> $fname
